### ISSUE TITLE
Slow redirect

### ISSUE THREAD

**Issue by Gdewilde** [closeio/closeio-api#107]
When integrating with the Close API, we need to include a forward slash at the end of every API call to avoid an unnecessary (+200ms) redirect. Is this correct?

Also listed at https://apitracker.io/a/closeio

**Comment by philfreo** [comment]
Yes, a trailing slash should be used on our REST endpoints as shown on https://developer.close.com/

This Python library takes care of that for you though, as you can see in the README example (due to code [like this](https://github.com/closeio/closeio-api/blob/e24601c962b56f7f5990201b86199ec5d903761c/closeio_api/__init__.py#L179))

**Comment by Gdewilde** [comment]
Thanks for the fast reply! This is indeed not applicable when using the Python SDK. It was more for developers not using the SDKs like us.
